# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from reports_api.swagger_server.models.base_model_ import Model
from reports_api.swagger_server.models.project_membership import ProjectMembership  # noqa: F401,E501
from reports_api.swagger_server.models.status200_ok_paginated import Status200OkPaginated  # noqa: F401,E501
from reports_api.swagger_server import util


class ProjectMemberships(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, limit: int=None, offset: int=None, size: int=None, status: int=200, total: int=None, type: str=None, data: List[ProjectMembership]=None):  # noqa: E501
        """ProjectMemberships - a model defined in Swagger

        :param limit: The limit of this ProjectMemberships.  # noqa: E501
        :type limit: int
        :param offset: The offset of this ProjectMemberships.  # noqa: E501
        :type offset: int
        :param size: The size of this ProjectMemberships.  # noqa: E501
        :type size: int
        :param status: The status of this ProjectMemberships.  # noqa: E501
        :type status: int
        :param total: The total of this ProjectMemberships.  # noqa: E501
        :type total: int
        :param type: The type of this ProjectMemberships.  # noqa: E501
        :type type: str
        :param data: The data of this ProjectMemberships.  # noqa: E501
        :type data: List[ProjectMembership]
        """
        self.swagger_types = {
            'limit': int,
            'offset': int,
            'size': int,
            'status': int,
            'total': int,
            'type': str,
            'data': List[ProjectMembership]
        }

        self.attribute_map = {
            'limit': 'limit',
            'offset': 'offset',
            'size': 'size',
            'status': 'status',
            'total': 'total',
            'type': 'type',
            'data': 'data'
        }
        self._limit = limit
        self._offset = offset
        self._size = size
        self._status = status
        self._total = total
        self._type = type
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'ProjectMemberships':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The projectMemberships of this ProjectMemberships.  # noqa: E501
        :rtype: ProjectMemberships
        """
        return util.deserialize_model(dikt, cls)

    @property
    def limit(self) -> int:
        """Gets the limit of this ProjectMemberships.


        :return: The limit of this ProjectMemberships.
        :rtype: int
        """
        return self._limit

    @limit.setter
    def limit(self, limit: int):
        """Sets the limit of this ProjectMemberships.


        :param limit: The limit of this ProjectMemberships.
        :type limit: int
        """

        self._limit = limit

    @property
    def offset(self) -> int:
        """Gets the offset of this ProjectMemberships.


        :return: The offset of this ProjectMemberships.
        :rtype: int
        """
        return self._offset

    @offset.setter
    def offset(self, offset: int):
        """Sets the offset of this ProjectMemberships.


        :param offset: The offset of this ProjectMemberships.
        :type offset: int
        """

        self._offset = offset

    @property
    def size(self) -> int:
        """Gets the size of this ProjectMemberships.


        :return: The size of this ProjectMemberships.
        :rtype: int
        """
        return self._size

    @size.setter
    def size(self, size: int):
        """Sets the size of this ProjectMemberships.


        :param size: The size of this ProjectMemberships.
        :type size: int
        """

        self._size = size

    @property
    def status(self) -> int:
        """Gets the status of this ProjectMemberships.


        :return: The status of this ProjectMemberships.
        :rtype: int
        """
        return self._status

    @status.setter
    def status(self, status: int):
        """Sets the status of this ProjectMemberships.


        :param status: The status of this ProjectMemberships.
        :type status: int
        """

        self._status = status

    @property
    def total(self) -> int:
        """Gets the total of this ProjectMemberships.


        :return: The total of this ProjectMemberships.
        :rtype: int
        """
        return self._total

    @total.setter
    def total(self, total: int):
        """Sets the total of this ProjectMemberships.


        :param total: The total of this ProjectMemberships.
        :type total: int
        """

        self._total = total

    @property
    def type(self) -> str:
        """Gets the type of this ProjectMemberships.


        :return: The type of this ProjectMemberships.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this ProjectMemberships.


        :param type: The type of this ProjectMemberships.
        :type type: str
        """

        self._type = type

    @property
    def data(self) -> List[ProjectMembership]:
        """Gets the data of this ProjectMemberships.


        :return: The data of this ProjectMemberships.
        :rtype: List[ProjectMembership]
        """
        return self._data

    @data.setter
    def data(self, data: List[ProjectMembership]):
        """Sets the data of this ProjectMemberships.


        :param data: The data of this ProjectMemberships.
        :type data: List[ProjectMembership]
        """

        self._data = data
