# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from reports_api.swagger_server.models.base_model_ import Model
from reports_api.swagger_server.models.project import Project  # noqa: F401,E501
from reports_api.swagger_server import util


class UserProjects(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, total: int=None, data: List[Project]=None):  # noqa: E501
        """UserProjects - a model defined in Swagger

        :param total: The total of this UserProjects.  # noqa: E501
        :type total: int
        :param data: The data of this UserProjects.  # noqa: E501
        :type data: List[Project]
        """
        self.swagger_types = {
            'total': int,
            'data': List[Project]
        }

        self.attribute_map = {
            'total': 'total',
            'data': 'data'
        }
        self._total = total
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'UserProjects':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The user_projects of this UserProjects.  # noqa: E501
        :rtype: UserProjects
        """
        return util.deserialize_model(dikt, cls)

    @property
    def total(self) -> int:
        """Gets the total of this UserProjects.


        :return: The total of this UserProjects.
        :rtype: int
        """
        return self._total

    @total.setter
    def total(self, total: int):
        """Sets the total of this UserProjects.


        :param total: The total of this UserProjects.
        :type total: int
        """

        self._total = total

    @property
    def data(self) -> List[Project]:
        """Gets the data of this UserProjects.


        :return: The data of this UserProjects.
        :rtype: List[Project]
        """
        return self._data

    @data.setter
    def data(self, data: List[Project]):
        """Sets the data of this UserProjects.


        :param data: The data of this UserProjects.
        :type data: List[Project]
        """

        self._data = data
