from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from reports_api.openapi_server.models.base_model import Model
from reports_api.openapi_server.models.user import User
from reports_api.openapi_server import util

from reports_api.openapi_server.models.user import User  # noqa: E501

class ProjectUsers(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, total=None, data=None):  # noqa: E501
        """ProjectUsers - a model defined in OpenAPI

        :param total: The total of this ProjectUsers.  # noqa: E501
        :type total: int
        :param data: The data of this ProjectUsers.  # noqa: E501
        :type data: List[User]
        """
        self.openapi_types = {
            'total': int,
            'data': List[User]
        }

        self.attribute_map = {
            'total': 'total',
            'data': 'data'
        }

        self._total = total
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'ProjectUsers':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The project_users of this ProjectUsers.  # noqa: E501
        :rtype: ProjectUsers
        """
        return util.deserialize_model(dikt, cls)

    @property
    def total(self) -> int:
        """Gets the total of this ProjectUsers.


        :return: The total of this ProjectUsers.
        :rtype: int
        """
        return self._total

    @total.setter
    def total(self, total: int):
        """Sets the total of this ProjectUsers.


        :param total: The total of this ProjectUsers.
        :type total: int
        """

        self._total = total

    @property
    def data(self) -> List[User]:
        """Gets the data of this ProjectUsers.


        :return: The data of this ProjectUsers.
        :rtype: List[User]
        """
        return self._data

    @data.setter
    def data(self, data: List[User]):
        """Sets the data of this ProjectUsers.


        :param data: The data of this ProjectUsers.
        :type data: List[User]
        """

        self._data = data
