from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from reports_api.openapi_server.models.base_model import Model
from reports_api.openapi_server.models.sliver import Sliver
from reports_api.openapi_server import util

from reports_api.openapi_server.models.sliver import Sliver  # noqa: E501

class SliceSlivers(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, total=None, data=None):  # noqa: E501
        """SliceSlivers - a model defined in OpenAPI

        :param total: The total of this SliceSlivers.  # noqa: E501
        :type total: int
        :param data: The data of this SliceSlivers.  # noqa: E501
        :type data: List[Sliver]
        """
        self.openapi_types = {
            'total': int,
            'data': List[Sliver]
        }

        self.attribute_map = {
            'total': 'total',
            'data': 'data'
        }

        self._total = total
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'SliceSlivers':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The slice_slivers of this SliceSlivers.  # noqa: E501
        :rtype: SliceSlivers
        """
        return util.deserialize_model(dikt, cls)

    @property
    def total(self) -> int:
        """Gets the total of this SliceSlivers.


        :return: The total of this SliceSlivers.
        :rtype: int
        """
        return self._total

    @total.setter
    def total(self, total: int):
        """Sets the total of this SliceSlivers.


        :param total: The total of this SliceSlivers.
        :type total: int
        """

        self._total = total

    @property
    def data(self) -> List[Sliver]:
        """Gets the data of this SliceSlivers.


        :return: The data of this SliceSlivers.
        :rtype: List[Sliver]
        """
        return self._data

    @data.setter
    def data(self, data: List[Sliver]):
        """Sets the data of this SliceSlivers.


        :param data: The data of this SliceSlivers.
        :type data: List[Sliver]
        """

        self._data = data
