from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from reports_api.openapi_server.models.base_model import Model
from reports_api.openapi_server.models.component import Component
from reports_api.openapi_server import util

from reports_api.openapi_server.models.component import Component  # noqa: E501

class SliverComponents(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, total=None, data=None):  # noqa: E501
        """SliverComponents - a model defined in OpenAPI

        :param total: The total of this SliverComponents.  # noqa: E501
        :type total: int
        :param data: The data of this SliverComponents.  # noqa: E501
        :type data: List[Component]
        """
        self.openapi_types = {
            'total': int,
            'data': List[Component]
        }

        self.attribute_map = {
            'total': 'total',
            'data': 'data'
        }

        self._total = total
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'SliverComponents':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The sliver_components of this SliverComponents.  # noqa: E501
        :rtype: SliverComponents
        """
        return util.deserialize_model(dikt, cls)

    @property
    def total(self) -> int:
        """Gets the total of this SliverComponents.


        :return: The total of this SliverComponents.
        :rtype: int
        """
        return self._total

    @total.setter
    def total(self, total: int):
        """Sets the total of this SliverComponents.


        :param total: The total of this SliverComponents.
        :type total: int
        """

        self._total = total

    @property
    def data(self) -> List[Component]:
        """Gets the data of this SliverComponents.


        :return: The data of this SliverComponents.
        :rtype: List[Component]
        """
        return self._data

    @data.setter
    def data(self, data: List[Component]):
        """Sets the data of this SliverComponents.


        :param data: The data of this SliverComponents.
        :type data: List[Component]
        """

        self._data = data
