# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from analytics_api.swagger_server.models.base_model_ import Model
from analytics_api.swagger_server.models.sliver import Sliver  # noqa: F401,E501
from analytics_api.swagger_server import util


class SliceSlivers(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, total: int=None, data: List[Sliver]=None):  # noqa: E501
        """SliceSlivers - a model defined in Swagger

        :param total: The total of this SliceSlivers.  # noqa: E501
        :type total: int
        :param data: The data of this SliceSlivers.  # noqa: E501
        :type data: List[Sliver]
        """
        self.swagger_types = {
            'total': int,
            'data': List[Sliver]
        }

        self.attribute_map = {
            'total': 'total',
            'data': 'data'
        }
        self._total = total
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'SliceSlivers':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The slice_slivers of this SliceSlivers.  # noqa: E501
        :rtype: SliceSlivers
        """
        return util.deserialize_model(dikt, cls)

    @property
    def total(self) -> int:
        """Gets the total of this SliceSlivers.


        :return: The total of this SliceSlivers.
        :rtype: int
        """
        return self._total

    @total.setter
    def total(self, total: int):
        """Sets the total of this SliceSlivers.


        :param total: The total of this SliceSlivers.
        :type total: int
        """

        self._total = total

    @property
    def data(self) -> List[Sliver]:
        """Gets the data of this SliceSlivers.


        :return: The data of this SliceSlivers.
        :rtype: List[Sliver]
        """
        return self._data

    @data.setter
    def data(self, data: List[Sliver]):
        """Sets the data of this SliceSlivers.


        :param data: The data of this SliceSlivers.
        :type data: List[Sliver]
        """

        self._data = data
