# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from analytics_api.swagger_server.models.base_model_ import Model
from analytics_api.swagger_server.models.component import Component  # noqa: F401,E501
from analytics_api.swagger_server import util


class SliverComponents(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, total: int=None, data: List[Component]=None):  # noqa: E501
        """SliverComponents - a model defined in Swagger

        :param total: The total of this SliverComponents.  # noqa: E501
        :type total: int
        :param data: The data of this SliverComponents.  # noqa: E501
        :type data: List[Component]
        """
        self.swagger_types = {
            'total': int,
            'data': List[Component]
        }

        self.attribute_map = {
            'total': 'total',
            'data': 'data'
        }
        self._total = total
        self._data = data

    @classmethod
    def from_dict(cls, dikt) -> 'SliverComponents':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The sliver_components of this SliverComponents.  # noqa: E501
        :rtype: SliverComponents
        """
        return util.deserialize_model(dikt, cls)

    @property
    def total(self) -> int:
        """Gets the total of this SliverComponents.


        :return: The total of this SliverComponents.
        :rtype: int
        """
        return self._total

    @total.setter
    def total(self, total: int):
        """Sets the total of this SliverComponents.


        :param total: The total of this SliverComponents.
        :type total: int
        """

        self._total = total

    @property
    def data(self) -> List[Component]:
        """Gets the data of this SliverComponents.


        :return: The data of this SliverComponents.
        :rtype: List[Component]
        """
        return self._data

    @data.setter
    def data(self, data: List[Component]):
        """Sets the data of this SliverComponents.


        :param data: The data of this SliverComponents.
        :type data: List[Component]
        """

        self._data = data
